### ISSUE TITLE
Sygjerim Per Veshje Te Policis V2

### ISSUE THREAD

**Issue by narcoo1** [3rion/Fivestar#40]
** Sygjerim Per Veshje Te Policis **
[Pasi Qe Policia Ka Shum Departmente Dhe Grada Te Ndryshme Ju Duhen Veshje Te Reja Per Tu Dalluar.]

** Ketu Mund Te Shihni Showcase Te Veshjeve  **
https://www.youtube.com/watch?v=UYCeyonmwVg
Perndryshe Modi Per Veshje Thirret EUP MENU LAW AND ORDER

Shpresoj Qe Keni Me Marr Parasysh Ket Sygjerim Edhe I Shtini Keto Veshje

**Comment by oljani** [comment]
O ebush ta kisha sygjeru nji kamion tjeter costum per te patrol per me e bo lojen ma real se pa lidhje kjo e gta-s scripti osh i leht 24.8 MB edhe i optimizum. 
![scania  1](https://user-images.githubusercontent.com/83887805/117555047-1920ec80-b05c-11eb-9e9a-340876dafbfd.png)
DM per scriptin : oljani 父#6598
