### ISSUE TITLE
Sygjerim Per Njesin E SWAT

### ISSUE THREAD

**Issue by ketamina997** [3rion/Fivestar#42]
** Sygjerim Per SWAT**
[Une Kisha Pasur Qef Qe SWAT Te Ket Nje Shield Per Vetmbrojtje Pasi Qe Duhet Te Ruajne Veten E Tyre.]

** Konteksti shtesë **
[Shtoni këtu ndonjë kontekst tjetër ose fotografi në lidhje me kërkesën tuaj.]
![image](https://user-images.githubusercontent.com/83889994/117556573-9fdcc600-b06a-11eb-8287-b9412cbbca87.jpeg)

https://github.com/xander1998/shield
👆👆👆👆👆👆
Scripti Per Shield

**Comment by REALSNAKKY** [comment]
**Me i Ba RAID Krejt GANGAT Ne Qytetin Fivestar Edhe Me Ja Kontrollu Gjdo Member Gang Ne Trung Ne Te Gjitha Makinat e Tyre Dhe Me i Konfisku Gjerat Qe Kan Brenda**
Dhe Ket Sen e Bajn **### _SWAT_**
