### ISSUE TITLE
Kerre te reja

### ISSUE THREAD

**Issue by Ilyrian** [3rion/Fivestar#52]
** Përshkruani veçorinë që dëshironi **
[Një përshkrim i qartë i asaj që dëshironi të shtohet. Përfshini çdo dokument, model ose ndonjë gjë tjetër në lidhje me idenë tuaj nëse është e mundur.] Besoj se kto kerre jon shum reale dhe shum tbukura edhe ishin pershtat per server. Edhe kisha than me hidis handlin/brakes tkerrit se IRL nuk osht handling si ku osht nserver, irl mun e kthen kerrin shpejt e sene, kshtyqe qiky sen osht shum keq

** Konteksti shtesë **
[Shtoni këtu ndonjë kontekst tjetër ose fotografi në lidhje me kërkesën tuaj.]
https://www.gta5-mods.com/vehicles/ferrari-812-superfast
https://www.gta5-mods.com/vehicles/2013-audi-s8-4-0tfsi-quattro
https://www.gta5-mods.com/vehicles/volkswagen-golf-mk6-5-door-addon-v0-1
https://www.gta5-mods.com/vehicles/brabus-g-class-g800
https://www.gta5-mods.com/vehicles/dodge-charger-hellcat-widebody-2021
https://www.gta5-mods.com/vehicles/mitsubishi-lancer-evolution-x-fq-400

**Comment by valdh** [comment]
GOLF 2 |GOLF 7|PASSAT| BMW X5,6| KETTO JAN SYGJERIMET E MIJA.https://www.gta5-mods.com/vehicles/volkswagen-golf-gti-2014-replace-unlocked | https://www.gta5-mods.com/vehicles/volkswagen-golf-mk3-gti-add-on-csq574 | https://www.gta5-mods.com/vehicles/bmw-x6m-f16
