### ISSUE TITLE
Shtrati i vendosur ne ambulanc

### ISSUE THREAD

**Issue by Ded1OneTap** [3rion/Fivestar#60]
0** Nje shtrat i cili do jet i vendosur ne ambulanc edhe te jet i levizshem**
[Kisha deshir qe ta boni nje shtrat te cilin do jet ivendosur ne  ambulanc qe kur e sherojm personin qe ta mos e shtijm ne ambulanc se pastaj po iken por ta vendosim ne shtrat e shtrati ta fusim ne ambulanc dhe shtrati te jet i levizshem sikur nje karroc dhe mendoj qe kjo ide  do jet nje menyr e nje RP te mrekullushme nga ana e EMS -ve.
Animacioni do jet i kryer nga ana jon qe eshte nen opsioni Vendos ne shtrat dhe vetem ne ta largojm  Largo nga shtrati 
Shtrati te jet i thjesht nuk dmth diqka i komplikuar.]

** Ja disa shembuj qe e kom pa **
 https://es.gta5-mods.com/misc/ems-medical-props 
https://pbs.twimg.com/media/EcLs4dpWkAIDiVJ.jpg 
https://pbs.twimg.com/media/EdbNAz5WoAA32qp.jpg
Me Rrezbegt 
Kledian Makolli

**Comment by Edi193123** [comment]
Me shti tesha t reja patika si air jordan 1 jordan shorce nike t nba e qisi sendesh ma drippy 

disa foto 
![image](https://user-images.githubusercontent.com/87243893/125173700-d21cb800-e1c0-11eb-859f-310453b32fcc.png)
 
 
![image](https://user-images.githubusercontent.com/87243893/125173714-e2349780-e1c0-11eb-8f08-81b4915a4bd3.png)


![image](https://user-images.githubusercontent.com/87243893/125173728-f37da400-e1c0-11eb-9437-3f28473ceb84.png)
