### ISSUE TITLE
Opsionin Search

### ISSUE THREAD

**Issue by Anonymous12345667** [3rion/Fivestar#61]
Kur e bejna rob dikend me mujt be search per gjerat e ati sepse ne nuk e dim qfar ka ai ne trup

**Comment by ermal3145** [comment]
Po de tani me bo lootbox ju apo,mja marr kejt senet qka i ka aj naper trup ti senet munesh mja rob veq qka i duhen karakterit tond ose najsen qe t duhet jo mu qu kejta senet mja kap

**Comment by valdh** [comment]
UNE PER OPSJONI SEARCH E KISHA PAS NI IDE ME SHTU OPSIONIN SEARCH AMA JO ME JA MARR PO VEQ ME JA KOFISKU QANTEN QE E KA SENDET.
