### ISSUE TITLE
Police Distress signal

### ISSUE THREAD

**Issue by Shukii1** [3rion/Fivestar#63]
** Përshkruani veçorinë që dëshironi **
Nese nje polic eshte i kidnapuar dhe radion e ka tkonfiskuar me pas nje buton distres signalit qe mos me kuptu ata qe polict jan te lajmruar qee kolega i tyre eshte ne rezik

** Konteksti shtesë **
skam ndonje foto te distress signalit

**Comment by REALSNAKKY** [comment]
Policia Me Dal Ne Rruget e Qytetit Fivestar Edhe Me Ba Kontroll Rutinore Gjdo Makine Qe e Posedojn Qytetaret e Fivestar Per Arsyje Se Ka Shum Vjedhje Ne Qytet,Krime,Vrasje Etj... 
Me i Ndalu Pak Ato
