### ISSUE TITLE
.

### ISSUE THREAD

**Issue by oljani** [3rion/Fivestar#64]
Me bo twiterin me fol per gjithcka si prsh per me shit sene ilegale kejt serverat e kan twiterin qashtu me fol se darkchat-in kerkush nuk e kshyrr.

**Comment by REALSNAKKY** [comment]
**Me i Ba RAID Krejt GANGAT Ne Qytetin Fivestar Edhe Me Ja Kontrollu Gjdo Member Gang Ne Trung Ne Te Gjitha Makinat e Tyre Dhe Me i Konfisku Gjerat Qe Kan Brenda**

**Comment by REALSNAKKY** [comment]
Policia Me Dal Ne Rruget e Qytetit Fivestar Edhe Me Ba Kontroll Rutinore Gjdo Makine Qe e Posedojn Qytetaret e Fivestar Per Arsyje Se Ka Shum Vjedhje Ne Qytet,Krime,Vrasje Etj...
Me i Ndalu Pak Ato
