### ISSUE TITLE
Sygjerim per vjedhje

### ISSUE THREAD

**Issue by Chris-Realy** [3rion/Fivestar#7]
Me mujt me ba ma film kur vjedhet nji bank ose jawerly me mujt me kon dhe nji makin tjt tu prit po te ket dy ven mrena ne at kerr qe dy vet tjer ti kapi policia nuk i dihet cilin kap a ate si ka paret a naj tjt dhe mos me ja bo impound kerrin po ta merrni tek stacioni policis dhe me e prit kur tvije me e marr me munu me e kap qashty.

**Comment by 3rion** [comment]
N'rregulla shkrun qe keni drejt me pas 1 ndihmes prej jashtit qe munet me ju prit me 1 makine, e sa per impound kush do qe osht pjese e vjedhjes te bankes osht kriminel kshtu qe sipas ligjit kerri shkon direkt ne impound :)
