### ISSUE TITLE
Sygjerim i morgit(Morgue)

### ISSUE THREAD

**Issue by ermal3145** [3rion/Fivestar#9]
** Përshkruani veçorinë që dëshironi **
[Sygjerim me shti morgin(morgue) dmth nese karakteri eshte pa ndjenja apo me gjakderdhje edhe nese aj person ka vendos me fshi qat karakter ka mundsi me bo roleplay me /me qe psh. Ska puls ose rrahjet e zemres jan reduktu me qu direkt doktori n morg se sun e pshton mo at person po edhe policia me pas mundsi me qu n morg personin psh nese e shef ni person tu ra prej ndertese a najsen aj duhet me shku direkt morg edhe me nejt aty disa dit,po edhe kur t jan me naj rast policia nese e rrok me plum n kry at person aj sun qohet mo direkt n morg.Ose nese e rrok naj person personin tjeter me plum n kok ato mo sun e pshton as dreqi kshtu qe direkt n morg edhe tani duhet me prit kur ti kryhen dit me pas muncin me kriju karakterin edhe ashtu besoj kejt e din qe kur t krijohet karakteri i hupin senet ati personit qe i ka pas permi veti(shpija,kerri) etj etj.]

** Konteksti shtesë **
[....]

**Comment by engjellahmeti1** [comment]
nuk ja vlen ashtu, punon 1 jav per diqka edhe met hup shum palidhje, morgun e kisha perdor veq kur don dikush me deshiren e ti

**Comment by ermal3145** [comment]
So ktu fontan e deshirash kur dush ti morgin duhet mu perdor kur t rrok dikush n kry edhe ato raste jon psh nese je pa ndjenja edhe ta fut plum nkry apo kupton

**Comment by engjellahmeti1** [comment]
me ja nis ashtu nuk lun kerkush me tu fshi krejt karakteri qdo 5 minuta, i hup kuptimi lojes, ska aty t’rrok n kry t’rrok n kam, deri sa t’dek komplet aty nuk rrzohesh, edhe sdi sa e din serveri osht esx(krejt lujn veq per pare) rrall ka qe bojn ashtu rp me mar peng polic mi qu n’mal veq per qef e sene

**Comment by ermal3145** [comment]
Po ti sdek meniren oj qyqe n rrema ti je pa ndjenja kur t bjen ntok qka je tu fol shko lexoj rregullat tani hajde komento ktu edhe morgin spe dishe hala qysh funksionin amo staffi e din

**Comment by engjellahmeti1** [comment]
> Po ti sdek meniren oj qyqe n rrema ti je pa ndjenja kur t bjen ntok qka je tu fol shko lexoj rregullat tani hajde komento ktu edhe morgin spe dishe hala qysh funksionin amo staffi e din

po sjem n’server tu bo rp per momentin ka ra n’tok pa ndjenja se kur foli per fjalen me
myt i bjen me plagos
